services:
  webserver:
    image: ghcr.io/waltertamboer/gitlab-timelogs:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gitlab-timelogs
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html